# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/product-service

# Eureka configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Spring Boot application name
spring.application.name=product-service

# Server port configuration
server.port=8084
